from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

DEFAULT_LOCALE = "en"
LOCALE_DIR = Path(__file__).resolve().parent / "locales"
DEFAULT_FILE = LOCALE_DIR / "zh_TW.json"
LOCALE_FILES = {
    "zh-tw": LOCALE_DIR / "zh_TW.json",
    "zh_cn": LOCALE_DIR / "zh_CN.json",
    "zh-cn": LOCALE_DIR / "zh_CN.json",
}


def load_catalog(path: str | Path | None = None) -> dict[str, Any]:
    target = Path(path) if path else DEFAULT_FILE
    if not target.exists():
        return {"locale": "en", "lookup": {}, "translations": {}}
    return json.loads(target.read_text(encoding="utf-8"))


def make_translator(locale: str = DEFAULT_LOCALE, path: str | Path | None = None):
    normalized = locale.lower()
    if normalized in {"en", "en-us", "en-gb"}:
        catalog = {}
    else:
        catalog_path = path or LOCALE_FILES.get(normalized, DEFAULT_FILE)
        catalog = load_catalog(catalog_path)
    lookup = catalog.get("lookup", {})

    def translate(text: str | None) -> str:
        if not text:
            return ""
        return lookup.get(text, text)

    # Used by translate_compound_name without making callers pass the catalog.
    translate.catalog = catalog  # type: ignore[attr-defined]
    return translate


def translate_item_text(text: str, translator) -> str:
    """Translate line-based PoB item text while preserving values and formatting."""
    lines = text.splitlines()
    translated: list[str] = []
    for line in lines:
        raw = line.strip()
        if not raw:
            translated.append(line)
            continue
        translated.append(translate_compound_name(raw, translator))
    return "\n".join(translated)


def translate_compound_name(name: str, translator) -> str:
    """Translate known unique/base names inside a PoB display name.

    Rare item names are custom generated by the player and normally have no
    official translation. The base item part can still be translated.
    """
    result = translator(name)
    if result != name:
        return result
    # Longest-first avoids translating a short token before its complete base.
    catalog = getattr(translator, "catalog", {})
    keys = sorted(catalog.get("lookup", {}), key=len, reverse=True)
    for key in keys:
        if not key or len(key) < 2 or key not in result:
            continue
        # 僅在英文單字邊界替換，避免 Spell 命中 Spells、Life 命中 Lifeless。
        if re.fullmatch(r"[A-Za-z0-9_ ]+", key):
            pattern = r"(?<![A-Za-z0-9_])" + re.escape(key) + r"(?![A-Za-z0-9_])"
            result = re.sub(pattern, catalog["lookup"][key], result)
        else:
            result = result.replace(key, catalog["lookup"][key])
    return result


def install_catalog(path: str | Path, destination: str | Path = DEFAULT_FILE) -> Path:
    """Validate and copy a generated catalog into the application location."""
    source = Path(path)
    data = load_catalog(source)
    if data.get("schema_version") != 1 or not isinstance(data.get("lookup"), dict):
        raise ValueError("不是 pob-cli schema_version=1 的翻譯 JSON")
    target = Path(destination)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return target
